# rustfmt configuration for slio-git

edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
merge_derives = true
use_small_heuristics = "Default"
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_comments = true
